#!/usr/bin/env -S npx tsx
import { promises as fs } from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const indexer = path.resolve(here, "../src/index.ts");

async function main() {
  const target = path.resolve(process.argv[2] ?? process.cwd());
  let gitRoot: string;
  try {
    gitRoot = execSync("git rev-parse --show-toplevel", { cwd: target }).toString().trim();
  } catch {
    console.error(`[codeindex] ${target} is not inside a git repository.`);
    process.exit(1);
  }

  const hookDir = path.join(gitRoot, ".git", "hooks");
  const hookPath = path.join(hookDir, "post-commit");

  const hook = `#!/usr/bin/env bash
# codeindex post-commit hook (auto-generated by scripts/install-hooks.ts).
# Async, non-blocking, incremental reindex of just-committed TS/TSX/MD files.

changed="$(git diff-tree --no-commit-id --name-only -r HEAD | grep -E '\\.(ts|tsx|md|mdx)$' || true)"
[ -z "$changed" ] && exit 0

ROOT="$(git rev-parse --show-toplevel)"
(
  cd "$ROOT" || exit 0
  mkdir -p .codeindex
  # shellcheck disable=SC2086
  npx tsx ${JSON.stringify(indexer)} --update $changed --root "$ROOT" >> .codeindex/update.log 2>&1
) >/dev/null 2>&1 &
disown 2>/dev/null || true
exit 0
`;

  await fs.mkdir(hookDir, { recursive: true });
  if (await fileExists(hookPath)) {
    await fs.copyFile(hookPath, hookPath + ".bak");
    console.error(`[codeindex] backed up existing hook -> post-commit.bak`);
  }
  await fs.writeFile(hookPath, hook, { mode: 0o755 });
  await fs.chmod(hookPath, 0o755);
  console.error(`[codeindex] installed post-commit hook at ${hookPath}`);
  console.error(`[codeindex] indexer: ${indexer}`);
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
